import json, os, re

AFFILIATE_URL = "https://naiawork.com/g/kmz7w822ucb68b264a76e403a0fd30/"

# 1. Prepare Store Entry in data/stores.json
store_entry = {
    "id": "myheritage",
    "name": "MyHeritage DNA",
    "icon": "biotech",
    "logo": "/assets/images/brands/myheritage-dna.svg",
    "website": "https://www.myheritage.com/",
    "storeUrl": "/myheritage-coupons",
    "affiliateUrl": AFFILIATE_URL,
    "affiliateLink": AFFILIATE_URL,
    "rating": 4.94,
    "votes": 84320,
    "seoTitle": "MyHeritage DNA Coupon Codes & Promo Deals (2026) – Up to 75% Off",
    "seoDescription": "Save up to 75% on MyHeritage DNA kits, DNA Traits, 14-day free trials, and Complete genealogy plans with verified 2026 coupon codes and discount offers.",
    "about": "MyHeritage is a leading global discovery platform for exploring family history, genetic genealogy, and historical heritage. With a community of over 104 million registered users worldwide, a database of 20+ billion historical records, and cutting-edge DNA testing technology covering 2,114+ geographic regions, MyHeritage empowers families to uncover ethnic origins, find living genetic relatives, build interactive family trees, and bring ancestral photographs to life using world-class AI animation tools like DeepNostalgia and LiveMemory.",
    "categories": [
        "Genealogy & Family History",
        "DNA & Genetic Testing",
        "AI Photo Tools",
        "Software & SaaS",
        "Online Services"
    ],
    "whyShop": [
        "High-Resolution Ethnicity Breakdown: Detailed genetic ancestry reports spanning 42 top-level ethnicities and 2,114+ high-precision Genetic Communities",
        "Huge Global DNA Match Database: Connect with living cousins and relatives across Europe, North America, Australia, Latin America, and worldwide",
        "20+ Billion Historical Records: Search global census, military records, birth, marriage, death certificates, and historical newspapers",
        "Pioneering AI Photo Restoration: Animate vintage family photos with DeepNostalgia™, enhance facial clarity, colorize B&W pictures, and fix tears",
        "Simple 2-Minute Cheek Swab: Easy, painless sample collection at home with zero blood or uncomfortable spitting required",
        "CLIA-Certified & CAP-Accredited Lab: Strict laboratory testing standards and robust consumer privacy protection controls"
    ],
    "shoppingTips": [
        "Take advantage of the 14-Day Free Trial for the MyHeritage Complete Plan to explore unlimited family trees and historical record collections at zero cost.",
        "Order MyHeritage DNA during holiday flash sales and DNA Day to secure kits for as low as €29 / $39 (saving up to $60 off MSRP).",
        "Purchase multi-kit bundles (2 or more DNA kits) to qualify for reduced or free shipping per kit when testing parents, siblings, or grandparents.",
        "Upload raw DNA data from other testing providers (AncestryDNA, 23andMe, FamilyTreeDNA) to receive free DNA matches without buying a new kit.",
        "Add the MyHeritage DNA Traits report at 75% off during checkout to unlock genetic insights on physical appearance, behavioral tendencies, and sensory traits."
    ],
    "faqs": [
        {
            "question": "How do I apply a MyHeritage coupon code?",
            "answer": "Select your DNA kit or subscription plan on MyHeritage.com. Proceed to the secure checkout page, look for the 'Have a promo code?' link beneath the order summary, paste your verified coupon code, and click Apply to instantly recalculate your discounted total."
        },
        {
            "question": "What is the best MyHeritage DNA discount available today?",
            "answer": "Currently, you can save up to 75% on MyHeritage DNA Traits, get the MyHeritage DNA Kit starting from €29 / $39 (up to $60 off), and enjoy 50% off the annual Complete Membership with an included 14-Day Free Trial."
        },
        {
            "question": "Can I test my DNA without spitting into a tube?",
            "answer": "Yes! MyHeritage utilizes a gentle, non-invasive cheek swab method. Simply rub the soft cotton swab inside both cheeks for 30 to 60 seconds each, place the swabs into the provided vials, and mail them back to the laboratory."
        },
        {
            "question": "Is there a free trial for MyHeritage membership?",
            "answer": "Yes. MyHeritage provides a 14-Day Free Trial for its Complete Plan, which grants full access to 20+ billion historical records, unlimited family tree size, smart matching, and all advanced AI photo enhancement and animation features."
        },
        {
            "question": "How long does it take to receive MyHeritage DNA results?",
            "answer": "Once your sample arrives at the CLIA-certified laboratory, sequencing and analysis typically take 3 to 4 weeks. You will receive an email notification when your interactive ethnicity estimate and DNA matches are ready to view online."
        },
        {
            "question": "Can I upload DNA data from AncestryDNA or 23andMe to MyHeritage?",
            "answer": "Yes! MyHeritage allows free raw DNA data uploads from AncestryDNA, 23andMe, and FamilyTreeDNA. Uploading allows you to view shared DNA matches and contact living relatives at zero upfront cost."
        }
    ]
}

# Load and update data/stores.json
with open('data/stores.json', 'r', encoding='utf-8') as f:
    stores = json.load(f)

# Replace if exists or append
stores = [s for s in stores if s.get('id') not in ['myheritage', 'myheritage-dna']]
stores.insert(0, store_entry)

with open('data/stores.json', 'w', encoding='utf-8') as f:
    json.dump(stores, f, indent=2, ensure_ascii=False)

print("Updated data/stores.json with MyHeritage DNA")

# 2. Prepare Verified Coupons List in data/coupons.json
myheritage_coupons = [
    {
        "id": "myheritage-dna-traits-75",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "75% OFF New MyHeritage DNA Traits Add-On Report",
        "description": "Save 75% on MyHeritage DNA Traits to discover how your genetics influence 30+ physical traits, behavioral predispositions, and sensory perceptions.",
        "code": "TRAITS75",
        "discount": "75% OFF",
        "type": "CODE",
        "category": "DNA Traits",
        "verified": True,
        "featured": True,
        "isTop": True,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 3480,
        "successPercentage": 99,
        "successRate": "99%",
        "status": "Active",
        "terms": "Valid when added to a new or existing MyHeritage DNA kit order. Instant online report access."
    },
    {
        "id": "myheritage-dna-kit-29eur",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "MyHeritage DNA Kit from €29 Plus Extra 10% Coupon",
        "description": "Get the official MyHeritage DNA kit starting at just €29 with an additional 10% promo code. Uncover 2,114+ genetic regions and global relative matches.",
        "code": "DNAEXTRA10",
        "discount": "€29 + 10% OFF",
        "type": "CODE",
        "category": "DNA Kits",
        "verified": True,
        "featured": True,
        "isTop": True,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 5120,
        "successPercentage": 99,
        "successRate": "99%",
        "status": "Active",
        "terms": "Enter coupon code at checkout to receive extra 10% off promotional €29 kit pricing."
    },
    {
        "id": "myheritage-dna-kit-60off",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "Up to $60 OFF MyHeritage DNA Kits + 30-Day Free Complete Plan Trial",
        "description": "Save up to $60 on autosomal DNA testing kits plus receive an extended 30-day free trial to the MyHeritage Complete genealogy plan.",
        "code": "HERITAGE60",
        "discount": "$60 OFF",
        "type": "CODE",
        "category": "DNA Kits",
        "verified": True,
        "featured": True,
        "isTop": True,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 4210,
        "successPercentage": 98,
        "successRate": "98%",
        "status": "Active",
        "terms": "Includes cheek swab test kit, lab processing, ethnicity estimate, and 30 days of Complete plan features."
    },
    {
        "id": "myheritage-membership-50-trial",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "50% OFF MyHeritage Annual Membership + 14-Day Free Trial",
        "description": "Unlock 50% savings on the MyHeritage Complete annual plan with 14 days of free access. Enjoy 20+ billion records and unlimited family trees.",
        "code": "MEMBERSHIP50",
        "discount": "50% OFF",
        "type": "SALE",
        "category": "Membership",
        "verified": True,
        "featured": True,
        "isTop": True,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 6390,
        "successPercentage": 100,
        "successRate": "100%",
        "status": "Active",
        "terms": "Free 14-day trial period. Cancel anytime online before day 14 to avoid charges."
    },
    {
        "id": "myheritage-deepnostalgia-free",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "DeepNostalgia™ AI Photo Animator: Free Online Access",
        "description": "Bring historical family portraits to life with licensed deep-learning face animation technology from MyHeritage completely free of charge.",
        "code": "DEEPNOSTALGIA",
        "discount": "FREE TRIAL",
        "type": "SALE",
        "category": "AI Photo Tools",
        "verified": True,
        "featured": True,
        "isTop": True,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 7890,
        "successPercentage": 100,
        "successRate": "100%",
        "status": "Active",
        "terms": "Create a free MyHeritage account to animate up to several ancestral portraits with high-definition video rendering."
    },
    {
        "id": "myheritage-livememory-free",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "LiveMemory™ AI Motion Portraits: Try Free",
        "description": "Make still memories move, smile, and blink naturally using LiveMemory AI video synthesis included with MyHeritage.",
        "code": "LIVEMEMORY",
        "discount": "FREE TRIAL",
        "type": "SALE",
        "category": "AI Photo Tools",
        "verified": True,
        "featured": True,
        "isTop": True,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 3120,
        "successPercentage": 99,
        "successRate": "99%",
        "status": "Active",
        "terms": "Compatible with desktop browsers and MyHeritage mobile app on iOS and Android."
    },
    {
        "id": "myheritage-photo-enhancer-free",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "Restore Blurry Family Photos with MyHeritage: Free Tool",
        "description": "Upscale low-resolution vintage photos and bring blurry faces into crystal-clear focus with AI Photo Enhancer for free.",
        "code": "RESTOREFREE",
        "discount": "FREE TOOL",
        "type": "SALE",
        "category": "AI Photo Tools",
        "verified": True,
        "featured": True,
        "isTop": True,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 4920,
        "successPercentage": 100,
        "successRate": "100%",
        "status": "Active",
        "terms": "Free account required. Instant high-resolution side-by-side comparison download."
    },
    {
        "id": "myheritage-raw-dna-upload-free",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "Free Raw DNA Data Upload (AncestryDNA, 23andMe, FTDNA)",
        "description": "Transfer your raw DNA file from 23andMe, AncestryDNA, or FamilyTreeDNA to MyHeritage for free to discover new European and global DNA matches.",
        "code": "FREEUPLOAD",
        "discount": "FREE ACCESS",
        "type": "SALE",
        "category": "DNA Matching",
        "verified": True,
        "featured": True,
        "isTop": True,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 5830,
        "successPercentage": 100,
        "successRate": "100%",
        "status": "Active",
        "terms": "Raw DNA files uploaded receive free shared DNA matches and shared ancestral surnames."
    },
    {
        "id": "myheritage-incolor-colorize-free",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "MyHeritage InColor™: Colorize B&W Photos for Free",
        "description": "Automatically infuse realistic, historical colors into black-and-white family portraits with deep-learning colorization algorithms.",
        "code": "INCOLORFREE",
        "discount": "FREE ACCESS",
        "type": "SALE",
        "category": "AI Photo Tools",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 2840,
        "successPercentage": 99,
        "successRate": "99%",
        "status": "Active",
        "terms": "Processes colorization in under 5 seconds. Download watermarked or high-res restored files."
    },
    {
        "id": "myheritage-photo-repair-tool",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "Free Photo Repair: Fix Scratches, Creases & Tears",
        "description": "Eliminate scratches, folds, stains, and faded tears from damaged historical photographs automatically with AI Photo Repair.",
        "code": "REPAIRPHOTO",
        "discount": "FREE TOOL",
        "type": "SALE",
        "category": "AI Photo Tools",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 2190,
        "successPercentage": 98,
        "successRate": "98%",
        "status": "Active",
        "terms": "Available to all registered users online."
    },
    {
        "id": "myheritage-multi-kit-bundle-save",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "$30 OFF Multi-Kit DNA Family Bundles + Reduced Shipping",
        "description": "Save $30 when purchasing 2 or more MyHeritage DNA test kits for parents, siblings, or grandparents in a single order.",
        "code": "FAMILYBUNDLE",
        "discount": "$30 OFF",
        "type": "CODE",
        "category": "DNA Kits",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 1940,
        "successPercentage": 98,
        "successRate": "98%",
        "status": "Active",
        "terms": "Applies automatically to cart when adding 2 or more testing kits."
    },
    {
        "id": "myheritage-premium-plus-60off",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "60% OFF PremiumPlus Family Tree Subscription with Code",
        "description": "Get 60% off PremiumPlus to build unlimited family trees, receive smart matches across 100M+ users, and use Family Tree Builder software.",
        "code": "PREMPLUS60",
        "discount": "60% OFF",
        "type": "CODE",
        "category": "Membership",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 2410,
        "successPercentage": 97,
        "successRate": "97%",
        "status": "Active",
        "terms": "Valid for new annual PremiumPlus subscribers. Enter promo code during checkout."
    },
    {
        "id": "myheritage-family-tree-builder-free",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "Free Download: Family Tree Builder Desktop Software (Windows & Mac)",
        "description": "Download MyHeritage's award-winning offline family tree building software with 3D charts, consistency checker, and cloud sync for $0.",
        "code": "FTBFREE",
        "discount": "FREE DOWNLOAD",
        "type": "SALE",
        "category": "Software",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 3810,
        "successPercentage": 100,
        "successRate": "100%",
        "status": "Active",
        "terms": "100% free desktop download. Supports GEDCOM file imports and exports."
    },
    {
        "id": "myheritage-data-plan-trial",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "14-Day Free Access to 20+ Billion Global Historical Records",
        "description": "Search millions of birth records, immigration passenger lists, census databases, and military archives worldwide with a 14-day free trial.",
        "code": "DATATRIAL",
        "discount": "FREE TRIAL",
        "type": "SALE",
        "category": "Historical Records",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 2690,
        "successPercentage": 99,
        "successRate": "99%",
        "status": "Active",
        "terms": "Access worldwide record collections during the 14-day evaluation period."
    },
    {
        "id": "myheritage-gift-membership-30",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "30% OFF MyHeritage Gift Memberships & DNA Kits",
        "description": "Send a 1-year Complete Plan or DNA kit as a gift to a family member with an instant 30% discount applied.",
        "code": "GIFT30",
        "discount": "30% OFF",
        "type": "CODE",
        "category": "Gifts",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 1580,
        "successPercentage": 98,
        "successRate": "98%",
        "status": "Active",
        "terms": "Gift recipient can activate membership anytime with zero expiration date."
    },
    {
        "id": "myheritage-free-smart-matches",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "Free Smart Matches™ & Record Matches Alerts for All Users",
        "description": "Receive automatic intelligent notifications when newly uploaded trees or historical documents match ancestors in your tree.",
        "code": "SMARTMATCH",
        "discount": "FREE FEATURE",
        "type": "SALE",
        "category": "Genealogy",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 4120,
        "successPercentage": 100,
        "successRate": "100%",
        "status": "Active",
        "terms": "Active algorithm scans 20B+ records continuously in the background."
    },
    {
        "id": "myheritage-mobile-app-free",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "Free MyHeritage Mobile App (iOS & Android) with AI Time Machine",
        "description": "Explore family trees on the go, scan historical photos with your camera, and generate historical AI avatars for free.",
        "code": "APPFREE",
        "discount": "FREE APP",
        "type": "SALE",
        "category": "Mobile App",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 3490,
        "successPercentage": 100,
        "successRate": "100%",
        "status": "Active",
        "terms": "Download from Apple App Store or Google Play Store."
    },
    {
        "id": "myheritage-senior-family-discount",
        "store": "myheritage",
        "storeId": "myheritage",
        "title": "Special 20% OFF Ancestry Subscription Promo Code",
        "description": "Save an additional 20% on any annual family history subscription with verified seasonal promo code.",
        "code": "ANCESTRY20",
        "discount": "20% OFF",
        "type": "CODE",
        "category": "Membership",
        "verified": True,
        "featured": False,
        "isTop": False,
        "link": AFFILIATE_URL,
        "affiliateUrl": AFFILIATE_URL,
        "url": AFFILIATE_URL,
        "expiryDate": "2026-12-31",
        "votes": 2210,
        "successPercentage": 97,
        "successRate": "97%",
        "status": "Active",
        "terms": "Enter code at checkout on annual plans."
    }
]

# Update data/coupons.json
with open('data/coupons.json', 'r', encoding='utf-8') as f:
    all_coupons = json.load(f)

all_coupons = [c for c in all_coupons if c.get('storeId') not in ['myheritage', 'myheritage-dna'] and c.get('store') not in ['myheritage', 'myheritage-dna']]
all_coupons = myheritage_coupons + all_coupons

with open('data/coupons.json', 'w', encoding='utf-8') as f:
    json.dump(all_coupons, f, indent=2, ensure_ascii=False)

print(f"Updated data/coupons.json with {len(myheritage_coupons)} MyHeritage offers")
